import Head from 'next/head'
import Image from 'next/image'
import Weather from '../components/weather'
import axios from 'axios'
import { useState } from 'react'
import { BsSearch } from 'react-icons/bs'
import clear from '../public/assets/clear.jpg'
import Spinner from '../components/Spinner'

export default function Home() {

  const [city, setCity ] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false)

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`


  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);

      axios.get(url).then((res)=>{
        setWeather(res.data);
        setLoading(false)
      })
    
  }

  if(loading) {
    return <Spinner />
    
  }
  else {
    return (
      <>
        <Head>
          <title>Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='absolute left-0 right-0 top-0 bottom-0 bg-black/40 z-[1]'/>
        <Image className='object-cover' src={clear} alt='clear weather and cloudy sky' layout='fill'/> 
        <div className='relative flex justify-between items-center max-w-[300px] w-full m-auto pt-4 text-white z-10 md:max-w-[500px]'>
          <form onSubmit={fetchWeather} className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 rounded-xl'>
            <div>
            <input onChange={(e)=>{setCity(e.target.value)}} className='bg-transparent text-white border-none focus:outline-none text-md placeholder:text-white' placeholder='Search City...' type='text'/>
            </div>
            <button onClick={fetchWeather}><BsSearch /></button>
          </form>
        </div>
        {weather.main && <Weather data={weather} />}

      </>
    )
  }
}
